[torch] Remove /tmp/pipcache from build workflows (#3378)
## Motivation

Following up on
https://github.com/ROCm/TheRock/pull/3303#discussion_r2793698012. The
pip cache is useful for local rebuilds but is not providing much value
on CI builds using ephemeral VMs running inside docker containers.

## Technical Details

The `pip cache remove rocm` command fails under the manylinux docker
container if an alternate cache directory is not provided:

```
Building PyTorch wheels for gfx94X-dcgpu
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
ERROR: pip cache commands can not function since cache is disabled.
Traceback (most recent call last):
  File "/__w/TheRock/TheRock/./external-builds/pytorch/build_prod_wheels.py", line 1078, in <module>
++ Exec [/__w/TheRock/TheRock]$ /opt/python/cp312-cp312/bin/python -m pip cache remove rocm_sdk
    main(sys.argv[1:])
  File "/__w/TheRock/TheRock/./external-builds/pytorch/build_prod_wheels.py", line 1074, in main
    args.func(args)
  File "/__w/TheRock/TheRock/./external-builds/pytorch/build_prod_wheels.py", line 348, in do_build
    do_install_rocm(args)
  File "/__w/TheRock/TheRock/./external-builds/pytorch/build_prod_wheels.py", line 302, in do_install_rocm
    run_command(
  File "/__w/TheRock/TheRock/./external-builds/pytorch/build_prod_wheels.py", line 175, in run_command
    subprocess.check_call(args, cwd=str(cwd), env=full_env)
  File "/opt/python/cp312-cp312/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/python/cp312-cp312/bin/python', '-m', 'pip', 'cache', 'remove', 'rocm_sdk']' returned non-zero exit status 1.
Error: Process completed with exit code 1.
```

Also fixed a small bug from https://github.com/ROCm/TheRock/pull/735
where `--cache-dir` was added twice to the `pip install` command

## Test Plan

Test workflow run:
https://github.com/ROCm/TheRock/actions/runs/21916360386/job/63284560496

## Test Result

```
Building PyTorch wheels for gfx94X-dcgpu
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
ERROR: pip cache commands can not function since cache is disabled.
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Looking in indexes: https://rocm.devreleases.amd.com/v2/gfx94X-dcgpu/
Collecting rocm==7.12.0a20260211 (from rocm[devel,libraries]==7.12.0a20260211)
  Downloading https://rocm.devreleases.amd.com/v2/gfx94X-dcgpu/rocm-7.12.0a20260211.tar.gz (16 kB)
```

(I think stdout/stderr output are not being interleaved fully, so the
new warning won't appear until later in the logs?)

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.

---------

Co-authored-by: Claude <noreply@anthropic.com>