Move non-sysdep third-party projects after base and compiler. (#2045)
## Motivation

This allows third-party deps to be built using our own amd-llvm
toolchain. This is a step towards a larger bootstrapping effort where we
should first build the compiler than use it consistently for all
subprojects.

* Fixes https://github.com/ROCm/TheRock/issues/2003 by building spdlog
with amd-llvm (instead of MSVC on Windows, which fails to build it)
* Unblocks https://github.com/ROCm/TheRock/pull/2599 since OpenMPI has
issues building using the system toolchain in our manylinux build
container that using our own amd-llvm toolchain may avoid

## Technical Details

This splits third-party into sysdeps and application libraries:
* sysdeps are needed to build the compiler and must be built using the
system toolchain (MSVC on Windows)
* application libraries can/should be built using a clang toolchain

For building spdlog on Windows, see how it sets the `/Zc:__cplusplus`
flag for MSVC (see [the code
here](https://github.com/gabime/spdlog/blob/3f7e50285936d8ba91d17650d94a2ab48d33169f/CMakeLists.txt#L296-L307))
and we don't want that propagating to later builds using clang.

## Test Plan

Try building spdlog and rocroller on Windows.

> [!NOTE]
> rocroller also needed these changes to try building on Windows:
https://github.com/ROCm/TheRock/compare/main...ScottTodd:TheRock:rocroller-windows-testing

## Test Result

* `therock-spdlog_configure.log` before:
  ```
  0.5	-- The CXX compiler identification is MSVC 19.44.35222.0
  0.7	-- Detecting CXX compiler ABI info
  1.7	-- Detecting CXX compiler ABI info - done
1.8 -- Check for working CXX compiler: C:/Program Files/Microsoft Visual
Studio/2022/Community/VC/Tools/MSVC/14.44.35207/bin/Hostx64/x64/cl.exe -
skipped
  ```
* ``therock-spdlog_configure.log`` after:
  ```
0.3 -- The CXX compiler identification is Clang 22.0.0 with GNU-like
command-line
  0.3	-- Detecting CXX compiler ABI info
  0.5	-- Detecting CXX compiler ABI info - done
0.5 -- Check for working CXX compiler:
D:/projects/TheRock/build/compiler/amd-llvm/dist/lib/llvm/bin/clang++.exe
- skipped
  ```
* `rocRoller_build.log` before
(https://gist.github.com/ScottTodd/791e5addeb02950e542cabf6b93e3ef0#file-rocroller_build_before_spdlog_toolchain_changes-log):
  ```
0.1 FAILED: [code=1]
GPUArchitectureGenerator/CMakeFiles/GPUArchitectureGenerator.dir/__/lib/source/GPUArchitecture.cpp.obj
0.1 ccache
D:\projects\TheRock\build\core\clr\dist\lib\llvm\bin\clang++.exe ...
--dependent-lib=msvcrt /Zc:__cplusplus -MD -MT ...
  0.1	clang++: error: no such file or directory: '/Zc:__cplusplus'
  ```
* `rocRoller_build.log` after
(https://gist.github.com/ScottTodd/791e5addeb02950e542cabf6b93e3ef0#file-rocroller_build_after_spdlog_toolchain_changes-log):
  ```
4.7 [8/441] Building CXX object
GPUArchitectureGenerator/CMakeFiles/GPUArchitectureGenerator.dir/__/lib/source/Assemblers/InProcessAssembler.cpp.obj
4.7 FAILED: [code=1]
GPUArchitectureGenerator/CMakeFiles/GPUArchitectureGenerator.dir/__/lib/source/Assemblers/InProcessAssembler.cpp.obj
4.7 ccache
D:\projects\TheRock\build\core\clr\dist\lib\llvm\bin\clang++.exe ...
--dependent-lib=msvcrt -MD -MT ...
4.7 In file included from
D:/projects/TheRock/rocm-libraries/shared/rocroller/lib/source/Assemblers/InProcessAssembler.cpp:33:
4.7 In file included from
D:/projects/TheRock/rocm-libraries/shared/rocroller/lib/include\rocRoller/GPUArchitecture/GPUArchitectureLibrary.hpp:41:
4.7 In file included from
D:/projects/TheRock/rocm-libraries/shared/rocroller/lib/include\rocRoller/GPUArchitecture/GPUArchitecture.hpp:39:
4.7 In file included from
D:/projects/TheRock/rocm-libraries/shared/rocroller/lib/include\rocRoller/DataTypes/DataTypes.hpp:41:
4.7
D:/projects/TheRock/rocm-libraries/shared/rocroller/lib/include\rocRoller/DataTypes/DataTypes_E8M0.hpp:57:17:
error: unknown type name 'uint'
  4.7	   57 |                 uint mantissa : 23;
  4.7	      |                 ^
  ```

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.