Revert "Add origami to TheRock" (#3222)
Reverts ROCm/TheRock#2813

This broke ROCm Python package tests (`rocm-sdk test`), see
https://github.com/ROCm/TheRock/issues/3220.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/__w/_tool/Python/3.12.12/x64/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: liborigami.so.1: cannot open shared object file: No such file or directory
testSharedLibrariesLoad (rocm_sdk.tests.libraries_test.ROCmLibrariesTest.testSharedLibrariesLoad) ... 
  testSharedLibrariesLoad (rocm_sdk.tests.libraries_test.ROCmLibrariesTest.testSharedLibrariesLoad) [Check shared library loads] (so_path=PosixPath('/__w/TheRock/TheRock/.venv/lib/python3.12/site-packages/_rocm_sdk_libraries_gfx94X_dcgpu/lib/python3.12/site-packages/origami/origami.cpython-312-x86_64-linux-gnu.so')) ... ERROR
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/__w/_tool/Python/3.12.12/x64/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: liborigami.so.1: cannot open shared object file: No such file or directory
```