[Python Requirements] Downgrade boto3 to <1.42.0 to match dvc[s3] version (#3024)
In the manylinux docker file we install dvc[s3]==3.62.0. The [s3] extra
includes AWS S3 support, which brings in aiobotocore as a dependency.
The current version of boto3 we install in `requirements.txt` is too
high to match with aiobotocore, resulting in the error message below.

Downgrading boto3 to `>=1.41.0,<1.42.0` resolves the conflict

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
Successfully installed MarkupSafe-3.0.3 backports-zstd-1.3.0 boto3-1.42.30 botocore-1.42.30 cfgv-3.5.0 distlib-0.4.0 identify-2.6.16 iniconfig-2.3.0 joblib-1.5.3 lit-18.1.8 mako-1.3.10 msgpack-1.1.2 nodeenv-1.10.0 pluggy-1.6.0 pre-commit-4.5.1 pytest-8.4.2 pytest-cmake-0.13.0 python-magic-0.4.27 pyzstd-0.19.1 s3transfer-0.16.0 setuptools-80.9.0 virtualenv-20.36.1 zstandard-0.25.0
aiobotocore 2.26.0 requires botocore<1.41.6,>=1.41.0, but you have botocore 1.42.30 which is incompatible.
```