[torch] Enable flash attention by default on Windows, refactor script (#7131)
## Motivation

* This compliments / supersedes
https://github.com/ROCm/TheRock/pull/7027
* Fixes https://github.com/ROCm/TheRock/issues/6965

This fixes `import torch` errors which started after switching to the
new torch scikit_build_core build system:
```
OSError: [WinError 126] The specified module could not be found.
Error loading ".../torch/lib/torch_hip.dll" or one of its dependencies.
```

## Technical Details

We traced this to Windows builds missing `aotriton_v2.dll` and
`liblzma.dll` but this was missed in local testing since flash attention
was still disabled by default on Windows (yet enabled on our CI).

Some related refactors/cleanups are included here:
* Centralize flag validation and directory existence checks for all
project build options (previously they would assert late)
* Merge `--enable-pytorch-flash-attention-windows` and
`--enable-pytorch-flash-attention-linux` flags and handling
* Drop support for torch <=2.10 following
https://github.com/ROCm/TheRock/pull/6890

## Test Plan

* Local Windows build with `python build_prod_wheels.py build
--pytorch-dir D:/b/pytorch --pytorch-rocm-arch=gfx1100` (aotriton
_enabled_)
* Local Windows build with `python build_prod_wheels.py build
--pytorch-dir D:/b/pytorch --pytorch-rocm-arch=gfx906` (aotriton
_disabled_)
* CI will test that PyTorch release branches (e.g. `release/2.12`) still
build
* Manually triggered Linux/Windows builds of PyTorch `release/2.12` (old
build system) and `nightly` (new build system)
* Linux gfx942, `release/2.12`:
https://github.com/ROCm/TheRock/actions/runs/31036158083
* Linux gfx942, `nightly`:
https://github.com/ROCm/TheRock/actions/runs/31036391496
* Windows gfx110X, `release/2.12`:
https://github.com/ROCm/TheRock/actions/runs/31036487964
* Windows gfx110X, `nightly`:
https://github.com/ROCm/TheRock/actions/runs/31036530875
* Windows gfx906, `nightly`:
https://github.com/ROCm/TheRock/actions/runs/31037859358

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/TheRock/blob/main/CONTRIBUTING.md.