Revert "Update inputs, test staging whls and publish to v2" (#3045)
Reverts ROCm/TheRock#2557

This broke releases using the `release_portable_linux_packages.yml`
workflow:
https://github.com/ROCm/TheRock/actions/runs/21236023290/job/61104164516#step:20:44

```
Run benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc
  with:
    workflow: build_linux_jax_wheels.yml
    inputs: { "amdgpu_family": "gfx94X-dcgpu",
    "python_version": "3.12",
    "release_type": "nightly",
    "s3_subdir": "v2",
    "s3_staging_subdir": "v2-staging",
    "cloudfront_staging_url": "https://rocm.nightlies.amd.com/v2-staging",
    "rocm_version": "7.12.0a20260122",
    "tar_url": "https://rocm.nightlies.amd.com/tarball/therock-dist-linux-gfx94X-dcgpu-7.12.0a20260122.tar.gz",
    "ref": ""
  }

...

🏃 Workflow Dispatch Action v1.2.4
🔎 Found workflow, id: 178566937, name: Build Portable Linux JAX Wheels, path: .github/workflows/build_linux_jax_wheels.yml
🚀 Calling GitHub API to dispatch workflow...
Error: Unexpected inputs provided: ["ref"] - https://docs.github.com/rest/actions/workflows#create-a-workflow-dispatch-event
```

I have some rough notes on how we could catch this with tooling:
https://github.com/ScottTodd/claude-rocm-workspace/blob/main/plans/github_actions_static_analysis.md